name: Main workflow
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-10.13]
    steps:
    - name: Create aktualizr bottle
      run: |
        brew tap advancedtelematic/otaconnect
        brew install --build-bottle aktualizr
        brew bottle --json --no-rebuild --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/2019.8/" aktualizr
        brew bottle --merge --write ./aktualizr--2019.8.mojave.bottle.json
        brew cat aktualizr > aktualizr.rb
        mkdir build
        mv aktualizr.rb aktualizr--2019.8.mojave* build/
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: aktualizr-bottle-files
        path: build
