name: Build macOS homebrew bottle for ota-cli
on: 
  release:
    types: [created]
jobs:
  macOS:
    name: Upload a file to release
    runs-on: macOS-10.14
    steps:
    - name: Attempt to auto-update recipe and build bottle
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/ota.rb
        RELEASE_URL="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/"
        brew install --verbose --build-bottle ./ota.rb
        echo "installed package with bottle"
        ls -lh
        brew bottle --json --no-rebuild --force-core-tap --root-url=${RELEASE_URL} ota
        ls -lh
        brew bottle --merge --write --no-commit ./ota--0.1.0.mojave.bottle.json
        ls -ls
        rm ota.rb
        echo "Bottle and recipe creation succeeded!"
        echo "You should now open a PR at https://github.com/advancedtelematic/homebrew/otaconnect"
        echo "Here's the new recipe. It's also attached to this job as an artifact."
        echo "------------------------------------------------------------------------------------"
        brew cat ota | tee ota.rb
        echo "------------------------------------------------------------------------------------"
        mv ota--0.1.0.mojave.bottle.tar.gz ota-0.1.0.mojave.bottle.tar.gz
    - name: Upload bottle to github release page
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
        AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        FILENAME=ota-0.1.0.mojave.bottle.tar.gz
        UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
        curl -sSL -H "${AUTH_HEADER}" -F "data=@${FILENAME}" "$UPLOAD_URL"
    - name: Save recipe as build artifact
      uses: actions/upload-artifact@master
      with:
        name: ota.rb
        path: ota.rb
