name: Release upload test 6
on: 
  release:
    types: [created]
jobs:
  macOS:
    name: Upload a file to release
    runs-on: macOS-10.14
    steps:
    - name: Attempt to auto-update recipe and build bottle
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
        VERSION=$(basename $GITHUB_REF)
        RELEASE_URL="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/"
        sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
        brew install --build-bottle ./aktualizr.rb
        brew bottle --json --no-rebuild --force-core-tap --root-url=${RELEASE_URL} aktualizr
        brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
        rm aktualizr.rb
        echo "Bottle and recipe creation succeeded!"
        echo "You should now open a PR at https://github.com/advancedtelematic/homebrew/otaconnect"
        echo "Here's the new recipe. It's also attached to this job as an artifact."
        echo "------------------------------------------------------------------------------------"
        brew cat aktualizr | tee aktualizr.rb
        echo "------------------------------------------------------------------------------------"
        mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
    - name: Upload bottle to github release page
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(basename $GITHUB_REF)
        RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
        AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        FILENAME=aktualizr-${VERSION}.mojave.bottle.tar.gz
        UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
        curl -sSL -H "${AUTH_HEADER}" -F "data=@${FILENAME}" "$UPLOAD_URL"
    - name: Save recipe as build artifact
      uses: actions/upload-artifact@master
      with:
        name: aktualizr.rb
        path: aktualizr.rb
        

# name: Main workflow
# on:
#   push:
#     tags:
#       - 20[1-2][0-9].[1-9]*
# jobs:
#   macOS:
#     name: Run macOS
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [macOS-10.14, macOS-10.13]
#     steps:
#     - name: Create aktualizr bottle from tag
#       run: |
#         curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
#         export VERSION=$(basename $GITHUB_REF)
#         sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
#         brew install --build-bottle ./aktualizr.rb
#         brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/" aktualizr
#         brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
#         brew cat aktualizr > aktualizr.rb
#         mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
#     - name: Upload bottle to github release page
#       run: |
#         export VERSION=$(echo $GITHUB_REF | cut -d'/' -f3-)
#         export FILENAME=aktualizr-${VERSION}.mojave.bottle.tar.gz
#         export UPLOAD_URL="https://uploads.github.com/repos/tkfu/homebrew-action-testing/releases/${VERSION}/assets?name=${FILENAME}&access_token=$GH_ACCESS_TOKEN"
#         curl --data-binary @"${FILENAME}" -H "Content-Type: application/octet-stream" "$UPLOAD_URL"
#     - name: Upload recipe
#       uses: actions/upload-artifact@master
#       with:
#         name: aktualizr-recipe
#         path: aktualizr.rb

  # macOS:
  #   name: Run macOS
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macOS-10.14, macOS-10.13]
  #   steps:
  #   - name: Create aktualizr bottle
  #     run: |
  #       brew tap advancedtelematic/otaconnect
  #       brew install --build-bottle aktualizr
  #       brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/2019.8/" aktualizr
  #       brew bottle --merge --write --no-commit ./aktualizr--2019.8.mojave.bottle.json
  #       brew cat aktualizr > aktualizr.rb
  #       mkdir build
  #       mv aktualizr.rb aktualizr--2019.8.mojave* build/
  #   - name: Upload build artifacts
  #     uses: actions/upload-artifact@master
  #     with:
  #       name: aktualizr-bottle-files
  #       path: build
