name: Build macOS homebrew bottle for ota-cli release page
on: 
  release:
    types: [created]
jobs:
  macOS:
    name: Build macOS homebrew bottle for ota-cli release page
    runs-on: macOS-10.14
    steps:
    - name: Attempt to auto-update recipe and build bottle
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/ota.rb
        VERSION=${GITHUB_REF#refs/tags/}
        RELEASE_URL="https://github.com/advancedtelematic/ota-cli/releases/download/${VERSION}"
        sed -i '' -E "s/  version \"[0-9]+.[0-9]+.[0-9]+\"/  version \"${VERSION}\"/" ota.rb
        brew install --build-bottle ./ota.rb
        brew bottle --json --no-rebuild --force-core-tap --root-url=${RELEASE_URL} ota
        brew bottle --merge --write --no-commit ./ota--${VERSION}.mojave.bottle.json
        rm ota.rb
        echo "Bottle and recipe creation succeeded!"
        echo "You should now open a PR at https://github.com/advancedtelematic/homebrew/otaconnect"
        echo "Here's the new recipe. It's also attached to this job as an artifact."
        echo "------------------------------------------------------------------------------------"
        brew cat ota | tee ota.rb
        echo "------------------------------------------------------------------------------------"
        mv ota--${VERSION}.mojave.bottle.tar.gz ota-${VERSION}.mojave.bottle.tar.gz
    - name: Upload bottle to github release page
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        brew install ghr 
        VERSION=${GITHUB_REF#refs/tags/}
        ghr -u "${GITHUB_REPOSITORY%/*}" -r "${GITHUB_REPOSITORY#*/}" ${VERSION} ota-${VERSION}.mojave.bottle.tar.gz
    - name: Save recipe as build artifact
      uses: actions/upload-artifact@master
      with:
        name: ota.rb
        path: ota.rb
    - name: Save bottle as build artifact
      uses: actions/upload-artifact@master
      with:
        name: ota-bottle
        path: ota-0.1.0.mojave.bottle.tar.gz
