name: Build bottle for homebrew release
on: 
  release:
    types: created
jobs:
  macOS:
    name: Upload a file to release
    runs-on: ${{ matrix.os }}
    steps:
    - name: Create aktualizr bottle from tag
      run: echo dummy
      # run: |
      #   curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
      #   VERSION=$(basename $GITHUB_REF)
      #   echo $VERSION
      #   export VERSION=$(basename $GITHUB_REF)
      #   sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
      #   brew install --build-bottle ./aktualizr.rb
      #   brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/" aktualizr
      #   brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
      #   brew cat aktualizr > aktualizr.rb
      #   mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
    - name: Upload bottle to github release page
      run: |
        VERSION=$(basename $GITHUB_REF)
        export VERSION=$(basename $GITHUB_REF)
        export RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
        export AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        export FILENAME=aktualizr-${VERSION}.mojave.bottle.tar.gz
        export UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
        echo "version = ${VERSION} release id = ${RELEASE_ID} filename = ${FILENAME}""
        echo "upload url = ${UPLOAD_URL}"
        echo "auth = ${AUTH_HEADER}"
        echo "test" > $FILENAME
        curl -sSL -H "${AUTH_HEADER}" -F "data=@${FILENAME}" "$UPLOAD_URL"
        

# name: Main workflow
# on:
#   push:
#     tags:
#       - 20[1-2][0-9].[1-9]*
# jobs:
#   macOS:
#     name: Run macOS
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [macOS-10.14, macOS-10.13]
#     steps:
#     - name: Create aktualizr bottle from tag
#       run: |
#         curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
#         export VERSION=$(basename $GITHUB_REF)
#         sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
#         brew install --build-bottle ./aktualizr.rb
#         brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/" aktualizr
#         brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
#         brew cat aktualizr > aktualizr.rb
#         mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
#     - name: Upload bottle to github release page
#       run: |
#         export VERSION=$(echo $GITHUB_REF | cut -d'/' -f3-)
#         export FILENAME=aktualizr-${VERSION}.mojave.bottle.tar.gz
#         export UPLOAD_URL="https://uploads.github.com/repos/tkfu/homebrew-action-testing/releases/${VERSION}/assets?name=${FILENAME}&access_token=$GH_ACCESS_TOKEN"
#         curl --data-binary @"${FILENAME}" -H "Content-Type: application/octet-stream" "$UPLOAD_URL"
#     - name: Upload recipe
#       uses: actions/upload-artifact@master
#       with:
#         name: aktualizr-recipe
#         path: aktualizr.rb

  # macOS:
  #   name: Run macOS
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macOS-10.14, macOS-10.13]
  #   steps:
  #   - name: Create aktualizr bottle
  #     run: |
  #       brew tap advancedtelematic/otaconnect
  #       brew install --build-bottle aktualizr
  #       brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/2019.8/" aktualizr
  #       brew bottle --merge --write --no-commit ./aktualizr--2019.8.mojave.bottle.json
  #       brew cat aktualizr > aktualizr.rb
  #       mkdir build
  #       mv aktualizr.rb aktualizr--2019.8.mojave* build/
  #   - name: Upload build artifacts
  #     uses: actions/upload-artifact@master
  #     with:
  #       name: aktualizr-bottle-files
  #       path: build
