name: Main workflow
on:
  push:
    tags:
      - 20[1-2][0-9].[1-9]*
jobs:
  macOS:
    name: Run macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-10.13]
    steps:
    - name: Create aktualizr bottle from tag
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
        export VERSION=$(echo $GITHUB_REF | cut -d'/' -f3-)
        echo $VERSION
        sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
        brew install --build-bottle ./aktualizr.rb
        brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/" aktualizr
        brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
        brew cat aktualizr > aktualizr.rb
        mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
    - name: Upload bottle
      uses: actions/upload-artifact@master
      with:
        name: aktualizr-bottle
        path: build


  # macOS:
  #   name: Run macOS
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macOS-10.14, macOS-10.13]
  #   steps:
  #   - name: Create aktualizr bottle
  #     run: |
  #       brew tap advancedtelematic/otaconnect
  #       brew install --build-bottle aktualizr
  #       brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/2019.8/" aktualizr
  #       brew bottle --merge --write --no-commit ./aktualizr--2019.8.mojave.bottle.json
  #       brew cat aktualizr > aktualizr.rb
  #       mkdir build
  #       mv aktualizr.rb aktualizr--2019.8.mojave* build/
  #   - name: Upload build artifacts
  #     uses: actions/upload-artifact@master
  #     with:
  #       name: aktualizr-bottle-files
  #       path: build
