name: Main workflow
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
    - name: Attempt to install aktualizr from bottle
      run: |
        brew tap advancedtelematic/otaconnect
        brew install aktualizr
    - name: Attempt to build aktualizr from source
      run: brew reinstall --build-from-source aktualizr
