name: Build bottle for homebrew release
on: release
jobs:
  macOS:
    name: Run macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-10.13]
    steps:
    - name: Create aktualizr bottle from tag
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
        VERSION=$(basename $GITHUB_REF)
        echo $VERSION
        export VERSION=$(basename $GITHUB_REF)
        sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
        brew install --build-bottle ./aktualizr.rb
        brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/" aktualizr
        brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
        brew cat aktualizr > aktualizr.rb
        mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
    - name: Upload bottle to github release page
      run: |
        brew install jq
        VERSION=$(basename $GITHUB_REF)
        echo $VERSION
        export VERSION=$(basename $GITHUB_REF)
        export RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
        export AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        export FILENAME=aktualizr-${VERSION}.mojave.bottle.tar.gz
        export UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
        curl -sSL -H "${AUTH_HEADER}" -F "data=@${FILENAME}" "$UPLOAD_URL"
        


