name: will this show?
on: push
jobs:
  macOS:
    name: Run macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-10.13]
    steps:
    - name: Create aktualizr bottle from tag
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
        VERSION=$(basename $GITHUB_REF)
        echo $VERSION
        export VERSION=$(basename $GITHUB_REF)
        sed -i '' -E "s/  version \"2019.[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
        #brew install --build-bottle ./aktualizr.rb
        brew bottle --json --no-rebuild --force-core-tap --root-url="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/" aktualizr
        brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
        brew cat aktualizr > aktualizr.rb
        mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
